"""
Export a project's gold layer for Power BI Desktop.

The web dashboards read Parquet compressed with zstd, aggregated down to exactly what each
page draws. Power BI wants the opposite: the row level star, so a user can slice it themselves,
which is the entire reason somebody asks for Power BI rather than a web page.

Two things are done differently here, and both exist because of how Power Query reads Parquet.

  Compression is snappy, not zstd. Power Query's Parquet reader has been reliable with snappy
  for years and support for newer codecs has varied by Desktop version. The web export keeps
  zstd because DuckDB-WASM reads it happily and the files are a third smaller over the wire.

  HUGEINT is cast down to BIGINT. DuckDB's sum() over an integer column returns a 128 bit
  integer, and Parquet has no native type for that, so it is written as a 38 digit decimal.
  Power Query either refuses it or silently turns it into a float. There are 27 such columns
  in Lumen's gold layer alone. Every one is a count of something small, so BIGINT loses
  nothing, and the cast is applied by inspecting the catalogue rather than by listing columns
  that would drift the moment a model changed.

Output is not committed. A .pbix stores its own copy of the data, so the workbook opens and
demos fine without these files; they are only needed to refresh it. Committing 15 MB of
row level Parquet per project to support a refresh that takes ten seconds to regenerate would
be the wrong trade.

    .venv/Scripts/python.exe scripts/export_powerbi.py
    .venv/Scripts/python.exe scripts/export_powerbi.py --project 02-kestrel-logistics
    .venv/Scripts/python.exe scripts/export_powerbi.py --all
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import duckdb

ROOT = Path(__file__).resolve().parent.parent

# The DuckDB file is named after the client, not the folder.
DB_NAME = {
    "01-meridian-provisions": "meridian.duckdb",
    "02-kestrel-logistics": "kestrel.duckdb",
    "03-sable-finch-credit": "sable.duckdb",
    "04-lumen-health": "lumen.duckdb",
}


def export(project: str) -> int:
    proj_dir = ROOT / "projects" / project
    db = proj_dir / DB_NAME[project]
    if not db.exists():
        print(f"  no warehouse at {db}. Run dbt build first.")
        return 1

    out = proj_dir / "powerbi" / "data"
    out.mkdir(parents=True, exist_ok=True)
    for stale in out.glob("*.parquet"):
        stale.unlink()

    con = duckdb.connect(str(db), read_only=True)
    tables = [r[0] for r in con.execute(
        "select table_name from information_schema.tables "
        "where table_schema = 'main_gold' order by table_name").fetchall()]

    print(f"\n{project}")
    total = 0
    manifest = []
    for t in tables:
        cols = con.execute(
            "select column_name, data_type from information_schema.columns "
            "where table_schema = 'main_gold' and table_name = ? "
            "order by ordinal_position", [t]).fetchall()

        # Cast only what needs it, and quote every identifier so a column called "year" or
        # "order" cannot break the generated SQL.
        select_list = ", ".join(
            f'"{c}"::bigint as "{c}"' if dt == "HUGEINT" else f'"{c}"'
            for c, dt in cols)
        narrowed = sum(1 for _, dt in cols if dt == "HUGEINT")

        dest = out / f"{t}.parquet"
        con.execute(
            f"copy (select {select_list} from main_gold.\"{t}\") "
            f"to '{dest.as_posix()}' (format parquet, compression snappy)")

        rows = con.execute(f'select count(*) from main_gold."{t}"').fetchone()[0]
        size = dest.stat().st_size
        total += size
        manifest.append((t, rows, size, narrowed))
        note = f"  {narrowed} narrowed" if narrowed else ""
        print(f"  {t:<26} {rows:>8,} rows {size / 1048576:>7.1f} MB{note}")

    print(f"\n  {len(tables)} tables, {total / 1048576:.1f} MB -> {out}")

    # One M query per table. Power BI has no way to import several queries from a file, so
    # these are written to be pasted one at a time into a blank query's Advanced Editor. The
    # folder is a parameter so the model keeps working when the repository moves.
    pq = proj_dir / "powerbi" / "queries.pq"
    lines = [
        "// Power Query for " + project,
        "// Generated by scripts/export_powerbi.py. Do not edit by hand, it is overwritten.",
        "//",
        "// First create a parameter, because hard coding the path into every query means",
        "// changing all of them when the repository moves:",
        "//",
        "//   Home > Manage Parameters > New Parameter",
        "//   Name: DataFolder   Type: Text   Current Value: " + str(out),
        "//",
        "// Then for each block below: Home > Get Data > Blank Query > Advanced Editor,",
        "// paste, and rename the query to match the table name in the comment.",
        "",
    ]
    for t, rows, _size, _n in manifest:
        lines += [
            f"// ---- {t}  ({rows:,} rows)",
            "let",
            f'    Source = Parquet.Document(File.Contents(DataFolder & "\\{t}.parquet"))',
            "in",
            "    Source",
            "",
        ]
    pq.write_text("\n".join(lines), encoding="utf-8")
    print(f"  Power Query written to {pq}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--project", default="04-lumen-health", choices=sorted(DB_NAME))
    ap.add_argument("--all", action="store_true", help="export every project")
    args = ap.parse_args()

    projects = sorted(DB_NAME) if args.all else [args.project]
    rc = 0
    for p in projects:
        rc |= export(p)
    return rc


if __name__ == "__main__":
    sys.exit(main())
